#ifndef __ADFFMPEG_ERRORS_H__
#define __ADFFMPEG_ERRORS_H__

#define ADFFMPEG_ERROR_HTTP_AUTH_REQUIRED               (-100)
#define ADFFMPEG_ERROR_DNS_HOST_RESOLUTION_FAILURE      (-101)
#define ADFFMPEG_ERROR_HOST_UNREACHABLE                 (-102)

#endif /* __ADFFMPEG_ERRORS_H__ */
