#ifndef __ADFFMPEG_ERRORS_H__
#define __ADFFMPEG_ERRORS_H__

enum ADHErrorCode
{
    ADFFMPEG_ERROR_NONE                               = 0,

    ADFFMPEG_DS_ERROR                                 = -99,
    ADFFMPEG_DS_ERROR_AUTH_REQUIRED                   = ADFFMPEG_DS_ERROR -1,
    ADFFMPEG_DS_ERROR_DNS_HOST_RESOLUTION_FAILURE     = ADFFMPEG_DS_ERROR -2,
    ADFFMPEG_DS_ERROR_HOST_UNREACHABLE                = ADFFMPEG_DS_ERROR -3,
    ADFFMPEG_DS_ERROR_INVALID_CREDENTIALS             = ADFFMPEG_DS_ERROR -4,
    ADFFMPEG_DS_ERROR_SOCKET                          = ADFFMPEG_DS_ERROR -5,
    ADFFMPEG_DS_ERROR_CREAT_CONECTION_TIMEOUT         = ADFFMPEG_DS_ERROR -6,

    ADFFMPEG_AD_ERROR                                 = -200,

    ADFFMPEG_AD_ERROR_UNKNOWN                         = ADFFMPEG_AD_ERROR -1,
    ADFFMPEG_AD_ERROR_READ_6_BYTE_SEPARATOR           = ADFFMPEG_AD_ERROR -2,
    ADFFMPEG_AD_ERROR_NEW_PACKET                      = ADFFMPEG_AD_ERROR -3,
    ADFFMPEG_AD_ERROR_PARSE_MIME_HEADER               = ADFFMPEG_AD_ERROR -4,
    //ADFFMPEG_AD_ERROR_NETVU_IMAGE_DATA                = ADFFMPEG_AD_ERROR -5,
    //ADFFMPEG_AD_ERROR_NETVU_AUDIO_DATA                = ADFFMPEG_AD_ERROR -6,

    ADFFMPEG_AD_ERROR_JPEG_IMAGE_DATA_READ            = ADFFMPEG_AD_ERROR -7,
    ADFFMPEG_AD_ERROR_JPEG_PIC_VERSION                = ADFFMPEG_AD_ERROR -8,
    //ADFFMPEG_AD_ERROR_JPEG_ALLOCATE_TEXT_BLOCK        = ADFFMPEG_AD_ERROR -9,
    ADFFMPEG_AD_ERROR_JPEG_READ_TEXT_BLOCK            = ADFFMPEG_AD_ERROR -10,
    ADFFMPEG_AD_ERROR_JPEG_HEADER                     = ADFFMPEG_AD_ERROR -11,
    ADFFMPEG_AD_ERROR_JPEG_NEW_PACKET                 = ADFFMPEG_AD_ERROR -12,
    ADFFMPEG_AD_ERROR_JPEG_READ_BODY                  = ADFFMPEG_AD_ERROR -13,

    ADFFMPEG_AD_ERROR_JFIF_NEW_PACKET                 = ADFFMPEG_AD_ERROR -14,
    ADFFMPEG_AD_ERROR_JFIF_GET_BUFFER                 = ADFFMPEG_AD_ERROR -15,
    ADFFMPEG_AD_ERROR_JFIF_MANUAL_SIZE                = ADFFMPEG_AD_ERROR -16,

    ADFFMPEG_AD_ERROR_MPEG4_MIME_NEW_PACKET           = ADFFMPEG_AD_ERROR -17,   
    ADFFMPEG_AD_ERROR_MPEG4_MIME_GET_BUFFER           = ADFFMPEG_AD_ERROR -18,
    ADFFMPEG_AD_ERROR_MPEG4_MIME_PARSE_HEADER         = ADFFMPEG_AD_ERROR -19,
    ADFFMPEG_AD_ERROR_MPEG4_MIME_PARSE_TEXT_DATA      = ADFFMPEG_AD_ERROR -20,
    ADFFMPEG_AD_ERROR_MPEG4_MIME_GET_TEXT_BUFFER      = ADFFMPEG_AD_ERROR -21,
    //ADFFMPEG_AD_ERROR_MPEG4_MIME_ALLOCATE_TEXT_BUFFER = ADFFMPEG_AD_ERROR -22,

    ADFFMPEG_AD_ERROR_MPEG4_GET_BUFFER                = ADFFMPEG_AD_ERROR -23,
    ADFFMPEG_AD_ERROR_MPEG4_PIC_VERSION_VALID         = ADFFMPEG_AD_ERROR -24,
    //ADFFMPEG_AD_ERROR_MPEG4_ALLOCATE_TEXT_BUFFER      = ADFFMPEG_AD_ERROR -25,
    ADFFMPEG_AD_ERROR_MPEG4_GET_TEXT_BUFFER           = ADFFMPEG_AD_ERROR -26,
    ADFFMPEG_AD_ERROR_MPEG4_NEW_PACKET                = ADFFMPEG_AD_ERROR -27,
    ADFFMPEG_AD_ERROR_MPEG4_PIC_BODY                  = ADFFMPEG_AD_ERROR -28,

    ADFFMPEG_AD_ERROR_MPEG4_MINIMAL_GET_BUFFER        = ADFFMPEG_AD_ERROR -29,
    ADFFMPEG_AD_ERROR_MPEG4_MINIMAL_NEW_PACKET        = ADFFMPEG_AD_ERROR -30,
    ADFFMPEG_AD_ERROR_MPEG4_MINIMAL_NEW_PACKET2       = ADFFMPEG_AD_ERROR -31,

    ADFFMPEG_AD_ERROR_MINIMAL_AUDIO_ADPCM_GET_BUFFER  = ADFFMPEG_AD_ERROR -32,
    ADFFMPEG_AD_ERROR_MINIMAL_AUDIO_ADPCM_NEW_PACKET  = ADFFMPEG_AD_ERROR -33,
    ADFFMPEG_AD_ERROR_MINIMAL_AUDIO_ADPCM_GET_BUFFER2 = ADFFMPEG_AD_ERROR -34,

    ADFFMPEG_AD_ERROR_AUDIO_ADPCM_GET_BUFFER          = ADFFMPEG_AD_ERROR -35,
    //ADFFMPEG_AD_ERROR_AUDIO_ADPCM_ALLOCATE_ADDITIONAL = ADFFMPEG_AD_ERROR -36,
    ADFFMPEG_AD_ERROR_AUDIO_ADPCM_GET_BUFFER2         = ADFFMPEG_AD_ERROR -37,

    ADFFMPEG_AD_ERROR_AUDIO_ADPCM_MIME_NEW_PACKET     = ADFFMPEG_AD_ERROR -38,
    ADFFMPEG_AD_ERROR_AUDIO_ADPCM_MIME_GET_BUFFER     = ADFFMPEG_AD_ERROR -39,

    ADFFMPEG_AD_ERROR_INFO_NEW_PACKET                 = ADFFMPEG_AD_ERROR -40,
    ADFFMPEG_AD_ERROR_INFO_GET_BUFFER                 = ADFFMPEG_AD_ERROR -41,

    ADFFMPEG_AD_ERROR_LAYOUT_NEW_PACKET               = ADFFMPEG_AD_ERROR -42,
    ADFFMPEG_AD_ERROR_LAYOUT_GET_BUFFER               = ADFFMPEG_AD_ERROR -43,

    ADFFMPEG_AD_ERROR_DEFAULT                         = ADFFMPEG_AD_ERROR -44,

    ADFFMPEG_AD_ERROR_GET_STREAM                      = ADFFMPEG_AD_ERROR -45,
    ADFFMPEG_AD_ERROR_GET_AUDIO_STREAM                = ADFFMPEG_AD_ERROR -46,
    ADFFMPEG_AD_ERROR_GET_INFO_LAYOUT_STREAM          = ADFFMPEG_AD_ERROR -47,
    //ADFFMPEG_AD_ERROR_END_OF_STREAM                   = ADFFMPEG_AD_ERROR -48,

    //ADFFMPEG_AD_ERROR_FAILED_TO_PARSE_INFOLIST        = ADFFMPEG_AD_ERROR -49,
    ADFFMPEG_AD_ERROR_OVERLAY_GET_BUFFER              = ADFFMPEG_AD_ERROR -50,
    ADFFMPEG_AD_ERROR_OVERLAY_PBM_READ                = ADFFMPEG_AD_ERROR -51,
    ADFFMPEG_AD_ERROR_GET_OVERLAY_STREAM              = ADFFMPEG_AD_ERROR -52,

    ADFFMPEG_AD_ERROR_LAST                            = ADFFMPEG_AD_ERROR -53,

	ADH_GRAPH_RELOAD_NEEDED                           = 0x8001,

#ifdef __midl
} ADHErrorCode;
#else
};
#endif

#endif
